// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-BYPzoyioJ4lp4zqp9juBaFIxykqaKL0',
    appId: '1:101863915802:android:87a82e2cd7384041636ca3',
    messagingSenderId: '101863915802',
    projectId: 'pozik-67ad7',
    storageBucket: 'pozik-67ad7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY4jz1sKAUxkp-BnwnYiA5PdbnZ-Tw2j0',
    appId: '1:101863915802:ios:b53b8c16a4d3d0f3636ca3',
    messagingSenderId: '101863915802',
    projectId: 'pozik-67ad7',
    storageBucket: 'pozik-67ad7.appspot.com',
    androidClientId: '101863915802-mehvugp5asc288nhvb5q4lng1p7ignc1.apps.googleusercontent.com',
    iosClientId: '101863915802-fg6iqe7p8vl72idc2rl4e9s9planv3tm.apps.googleusercontent.com',
    iosBundleId: 'es.pozik.pozikFront',
  );
}
